CREATE TABLE WYK_DZIAL(
D_ID INT PRIMARY KEY,
NAZWA VARCHAR(30),
K_ID INT
);

CREATE TABLE WYK_PRAC (
P_ID INT PRIMARY KEY,
IMIE VARCHAR(30),
NAZWISKO VARCHAR(50),
PENSJA NUMERIC(8,2),
D_ID INT REFERENCES WYK_DZIAL(D_ID)
);


INSERT INTO WYK_DZIAL (D_ID,NAZWA,K_ID) VALUES (1,'Dzial 1',8);
INSERT INTO WYK_DZIAL (D_ID,NAZWA,K_ID) VALUES (2,'Dzial 2',8);
INSERT INTO WYK_DZIAL (D_ID,NAZWA,K_ID) VALUES (3,'Dzial 3',4);
INSERT INTO WYK_DZIAL (D_ID,NAZWA,K_ID) VALUES (4,'Dzial 4',2);
INSERT INTO WYK_DZIAL (D_ID,NAZWA,K_ID) VALUES (5,'Dzial 5',1);
INSERT INTO WYK_DZIAL (D_ID,NAZWA,K_ID) VALUES (6,'HR',1);


INSERT INTO WYK_PRAC (P_ID,IMIE,NAZWISKO,PENSJA,D_ID) VALUES (1,'Yvonne','Tellus',1192.50,1);
INSERT INTO WYK_PRAC (P_ID,IMIE,NAZWISKO,PENSJA,D_ID) VALUES (2,'Francis','Purus',3068.3,2);
INSERT INTO WYK_PRAC (P_ID,IMIE,NAZWISKO,PENSJA,D_ID) VALUES (3,'Leigh','Enim',4930.00,3);
INSERT INTO WYK_PRAC (P_ID,IMIE,NAZWISKO,PENSJA,D_ID) VALUES (4,'Garrison','Penatibus','1954',4);
INSERT INTO WYK_PRAC (P_ID,IMIE,NAZWISKO,PENSJA,D_ID) VALUES (5,'Shaine','Ligula','5139.23',5);
INSERT INTO WYK_PRAC (P_ID,IMIE,NAZWISKO,PENSJA,D_ID) VALUES (6,'Kelly','Blandit','4886','6');
INSERT INTO WYK_PRAC (P_ID,IMIE,NAZWISKO,PENSJA,D_ID) VALUES (7,'Xander','At','3333',5);
INSERT INTO WYK_PRAC (P_ID,IMIE,NAZWISKO,PENSJA,D_ID) VALUES (8,'Jan','Kowalski','5576','2');
INSERT INTO WYK_PRAC (P_ID,IMIE,NAZWISKO,PENSJA,D_ID) VALUES (9,'Charlotte','Rutrum','5481','3');
INSERT INTO WYK_PRAC (P_ID,IMIE,NAZWISKO,PENSJA,D_ID) VALUES (10,'Robert','Non','1655','1');
INSERT INTO WYK_PRAC (P_ID,IMIE,NAZWISKO,PENSJA,D_ID) VALUES (11,'Blaine','Vivamus','2754','1');
INSERT INTO WYK_PRAC (P_ID,IMIE,NAZWISKO,PENSJA,D_ID) VALUES (12,'Yeo','Consectetuer','5423','2');
INSERT INTO WYK_PRAC (P_ID,IMIE,NAZWISKO,PENSJA,D_ID) VALUES (13,'Fleur','Aliquam','3536','3');
INSERT INTO WYK_PRAC (P_ID,IMIE,NAZWISKO,PENSJA,D_ID) VALUES (14,'Burton','Libero','4840','4');
INSERT INTO WYK_PRAC (P_ID,IMIE,NAZWISKO,PENSJA,D_ID) VALUES (15,'Cleo','Sit','3928','5');
INSERT INTO WYK_PRAC (P_ID,IMIE,NAZWISKO,PENSJA,D_ID) VALUES (16,'Aubrey','Et','2881','6');
INSERT INTO WYK_PRAC (P_ID,IMIE,NAZWISKO,PENSJA,D_ID) VALUES (17,'Summer','Imperdiet','3529','2');
INSERT INTO WYK_PRAC (P_ID,IMIE,NAZWISKO,PENSJA,D_ID) VALUES (18,'Ria','Odio','2187','1');
INSERT INTO WYK_PRAC (P_ID,IMIE,NAZWISKO,PENSJA,D_ID) VALUES (19,'Kitra','Ornare','2890','1');
INSERT INTO WYK_PRAC (P_ID,IMIE,NAZWISKO,PENSJA,D_ID) VALUES (20,'Wanda','Sollicitudin','3184','3');
INSERT INTO WYK_PRAC (P_ID,IMIE,NAZWISKO,PENSJA,D_ID) VALUES (21,'Naomi','Libero','2945','4');
INSERT INTO WYK_PRAC (P_ID,IMIE,NAZWISKO,PENSJA,D_ID) VALUES (22,'Peter','At','4026','5');
INSERT INTO WYK_PRAC (P_ID,IMIE,NAZWISKO,PENSJA,D_ID) VALUES (23,'Giselle','Ultrices','1760','6');
INSERT INTO WYK_PRAC (P_ID,IMIE,NAZWISKO,PENSJA,D_ID) VALUES (24,'Grady','Dignissim','3043','6');
INSERT INTO WYK_PRAC (P_ID,IMIE,NAZWISKO,PENSJA,D_ID) VALUES (25,'Ezekiel','Tellus','5026','2');
INSERT INTO WYK_PRAC (P_ID,IMIE,NAZWISKO,PENSJA,D_ID) VALUES (26,'Stuart','Nisi','3464','2');
INSERT INTO WYK_PRAC (P_ID,IMIE,NAZWISKO,PENSJA,D_ID) VALUES (27,'Halee','Mollis','3338','1');
INSERT INTO WYK_PRAC (P_ID,IMIE,NAZWISKO,PENSJA,D_ID) VALUES (28,'Zia','Tincidunt','5093','1');
INSERT INTO WYK_PRAC (P_ID,IMIE,NAZWISKO,PENSJA,D_ID) VALUES (29,'Madonna','Sem,','4752','1');
INSERT INTO WYK_PRAC (P_ID,IMIE,NAZWISKO,PENSJA,D_ID) VALUES (30,'Chanda','Amet','4516','3');
INSERT INTO WYK_PRAC (P_ID,IMIE,NAZWISKO,PENSJA,D_ID) VALUES (31,'Knox','Laoreet,','4078','4');
INSERT INTO WYK_PRAC (P_ID,IMIE,NAZWISKO,PENSJA,D_ID) VALUES (32,'Stephen','Nullam','4728','5');
INSERT INTO WYK_PRAC (P_ID,IMIE,NAZWISKO,PENSJA,D_ID) VALUES (33,'Jameson','At,','2757','6');
INSERT INTO WYK_PRAC (P_ID,IMIE,NAZWISKO,PENSJA,D_ID) VALUES (34,'Jesse','Id','5486','4');
INSERT INTO WYK_PRAC VALUES(35, 'Anna', 'Nowak', 4000, 2);
 